# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: household.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='household.proto',
  package='models',
  serialized_pb=_b('\n\x0fhousehold.proto\x12\x06models\"\xa6\x01\n\x06Parent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x34\n\x11\x63hildren_and_pets\x18\x02 \x03(\x0b\x32\x19.models.Parent.ChildOrPet\x1aX\n\nChildOrPet\x12\x1e\n\x05\x63hild\x18\x01 \x01(\x0b\x32\r.models.ChildH\x00\x12\x1a\n\x03pet\x18\x02 \x01(\x0b\x32\x0b.models.PetH\x00\x42\x0e\n\x0c\x63hild_or_pet\":\n\x05\x43hild\x12\x0c\n\x04name\x18\x01 \x02(\t\x12#\n\tinterests\x18\x02 \x03(\x0b\x32\x10.models.Interest\"S\n\x08Interest\x12\x0e\n\x06rating\x18\x01 \x02(\x05\x12\x1d\n\x13progamming_language\x18\x02 \x01(\tH\x00\x12\x0f\n\x05sport\x18\x03 \x01(\tH\x00\x42\x07\n\x05hobby\";\n\x03Pet\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x03\x64og\x18\x02 \x01(\x08H\x00\x12\r\n\x03\x63\x61t\x18\x03 \x01(\x08H\x00\x42\x08\n\x06\x61nimal')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARENT_CHILDORPET = _descriptor.Descriptor(
  name='ChildOrPet',
  full_name='models.Parent.ChildOrPet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='child', full_name='models.Parent.ChildOrPet.child', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pet', full_name='models.Parent.ChildOrPet.pet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='child_or_pet', full_name='models.Parent.ChildOrPet.child_or_pet',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=106,
  serialized_end=194,
)

_PARENT = _descriptor.Descriptor(
  name='Parent',
  full_name='models.Parent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Parent.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children_and_pets', full_name='models.Parent.children_and_pets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PARENT_CHILDORPET, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=194,
)


_CHILD = _descriptor.Descriptor(
  name='Child',
  full_name='models.Child',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Child.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interests', full_name='models.Child.interests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=254,
)


_INTEREST = _descriptor.Descriptor(
  name='Interest',
  full_name='models.Interest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rating', full_name='models.Interest.rating', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progamming_language', full_name='models.Interest.progamming_language', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sport', full_name='models.Interest.sport', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='hobby', full_name='models.Interest.hobby',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=256,
  serialized_end=339,
)


_PET = _descriptor.Descriptor(
  name='Pet',
  full_name='models.Pet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='models.Pet.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dog', full_name='models.Pet.dog', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cat', full_name='models.Pet.cat', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='animal', full_name='models.Pet.animal',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=341,
  serialized_end=400,
)

_PARENT_CHILDORPET.fields_by_name['child'].message_type = _CHILD
_PARENT_CHILDORPET.fields_by_name['pet'].message_type = _PET
_PARENT_CHILDORPET.containing_type = _PARENT
_PARENT_CHILDORPET.oneofs_by_name['child_or_pet'].fields.append(
  _PARENT_CHILDORPET.fields_by_name['child'])
_PARENT_CHILDORPET.fields_by_name['child'].containing_oneof = _PARENT_CHILDORPET.oneofs_by_name['child_or_pet']
_PARENT_CHILDORPET.oneofs_by_name['child_or_pet'].fields.append(
  _PARENT_CHILDORPET.fields_by_name['pet'])
_PARENT_CHILDORPET.fields_by_name['pet'].containing_oneof = _PARENT_CHILDORPET.oneofs_by_name['child_or_pet']
_PARENT.fields_by_name['children_and_pets'].message_type = _PARENT_CHILDORPET
_CHILD.fields_by_name['interests'].message_type = _INTEREST
_INTEREST.oneofs_by_name['hobby'].fields.append(
  _INTEREST.fields_by_name['progamming_language'])
_INTEREST.fields_by_name['progamming_language'].containing_oneof = _INTEREST.oneofs_by_name['hobby']
_INTEREST.oneofs_by_name['hobby'].fields.append(
  _INTEREST.fields_by_name['sport'])
_INTEREST.fields_by_name['sport'].containing_oneof = _INTEREST.oneofs_by_name['hobby']
_PET.oneofs_by_name['animal'].fields.append(
  _PET.fields_by_name['dog'])
_PET.fields_by_name['dog'].containing_oneof = _PET.oneofs_by_name['animal']
_PET.oneofs_by_name['animal'].fields.append(
  _PET.fields_by_name['cat'])
_PET.fields_by_name['cat'].containing_oneof = _PET.oneofs_by_name['animal']
DESCRIPTOR.message_types_by_name['Parent'] = _PARENT
DESCRIPTOR.message_types_by_name['Child'] = _CHILD
DESCRIPTOR.message_types_by_name['Interest'] = _INTEREST
DESCRIPTOR.message_types_by_name['Pet'] = _PET

Parent = _reflection.GeneratedProtocolMessageType('Parent', (_message.Message,), dict(

  ChildOrPet = _reflection.GeneratedProtocolMessageType('ChildOrPet', (_message.Message,), dict(
    DESCRIPTOR = _PARENT_CHILDORPET,
    __module__ = 'household_pb2'
    # @@protoc_insertion_point(class_scope:models.Parent.ChildOrPet)
    ))
  ,
  DESCRIPTOR = _PARENT,
  __module__ = 'household_pb2'
  # @@protoc_insertion_point(class_scope:models.Parent)
  ))
_sym_db.RegisterMessage(Parent)
_sym_db.RegisterMessage(Parent.ChildOrPet)

Child = _reflection.GeneratedProtocolMessageType('Child', (_message.Message,), dict(
  DESCRIPTOR = _CHILD,
  __module__ = 'household_pb2'
  # @@protoc_insertion_point(class_scope:models.Child)
  ))
_sym_db.RegisterMessage(Child)

Interest = _reflection.GeneratedProtocolMessageType('Interest', (_message.Message,), dict(
  DESCRIPTOR = _INTEREST,
  __module__ = 'household_pb2'
  # @@protoc_insertion_point(class_scope:models.Interest)
  ))
_sym_db.RegisterMessage(Interest)

Pet = _reflection.GeneratedProtocolMessageType('Pet', (_message.Message,), dict(
  DESCRIPTOR = _PET,
  __module__ = 'household_pb2'
  # @@protoc_insertion_point(class_scope:models.Pet)
  ))
_sym_db.RegisterMessage(Pet)


# @@protoc_insertion_point(module_scope)
